CLASS zcl_Ident DEFINITION PUBLIC.
* Generated by abap-openapi-client
* Ident, 1.0
  PUBLIC SECTION.
    INTERFACES zif_Ident.
    METHODS constructor IMPORTING ii_client TYPE REF TO if_http_client.
  PROTECTED SECTION.
    DATA mi_client TYPE REF TO if_http_client.
    DATA mo_json TYPE REF TO zcl_oapi_json.
    METHODS send_receive RETURNING VALUE(rv_code) TYPE i.
    METHODS parse_createapplicationrequest
      IMPORTING iv_prefix TYPE string
      RETURNING VALUE(createapplicationrequest) TYPE zif_Ident=>createapplicationrequest
      RAISING cx_static_check.
    METHODS parse_associateusertoapplicati
      IMPORTING iv_prefix TYPE string
      RETURNING VALUE(associateusertoapplicationrequ) TYPE zif_Ident=>associateusertoapplicationrequ
      RAISING cx_static_check.
    METHODS parse_updateapplicationrequest
      IMPORTING iv_prefix TYPE string
      RETURNING VALUE(updateapplicationrequest) TYPE zif_Ident=>updateapplicationrequest
      RAISING cx_static_check.
    METHODS parse_createorganizationreques
      IMPORTING iv_prefix TYPE string
      RETURNING VALUE(createorganizationrequest) TYPE zif_Ident=>createorganizationrequest
      RAISING cx_static_check.
    METHODS parse_updateorganizationdetail
      IMPORTING iv_prefix TYPE string
      RETURNING VALUE(updateorganizationdetailsreque) TYPE zif_Ident=>updateorganizationdetailsreque
      RAISING cx_static_check.
    METHODS parse_authorizelong_termtokenr
      IMPORTING iv_prefix TYPE string
      RETURNING VALUE(authorizelong_termtokenrequest) TYPE zif_Ident=>authorizelong_termtokenrequest
      RAISING cx_static_check.
    METHODS parse_authenticationrequest
      IMPORTING iv_prefix TYPE string
      RETURNING VALUE(authenticationrequest) TYPE zif_Ident=>authenticationrequest
      RAISING cx_static_check.
    METHODS parse_createuserrequest
      IMPORTING iv_prefix TYPE string
      RETURNING VALUE(createuserrequest) TYPE zif_Ident=>createuserrequest
      RAISING cx_static_check.
    METHODS parse_updateuserrequest
      IMPORTING iv_prefix TYPE string
      RETURNING VALUE(updateuserrequest) TYPE zif_Ident=>updateuserrequest
      RAISING cx_static_check.
ENDCLASS.

CLASS zcl_Ident IMPLEMENTATION.
  METHOD constructor.
    mi_client = ii_client.
  ENDMETHOD.

  METHOD send_receive.
    mi_client->send( ).
    mi_client->receive( ).
    mi_client->response->get_status( IMPORTING code = rv_code ).
  ENDMETHOD.

  METHOD parse_createapplicationrequest.
    createapplicationrequest-name = mo_json->value_string( iv_prefix && '/name' ).
  ENDMETHOD.

  METHOD parse_associateusertoapplicati.
    associateusertoapplicationrequ-user_id = mo_json->value_string( iv_prefix && '/user_id' ).
  ENDMETHOD.

  METHOD parse_updateapplicationrequest.
    updateapplicationrequest-name = mo_json->value_string( iv_prefix && '/name' ).
    updateapplicationrequest-description = mo_json->value_string( iv_prefix && '/description' ).
    updateapplicationrequest-type = mo_json->value_string( iv_prefix && '/type' ).
    updateapplicationrequest-hidden = mo_json->value_boolean( iv_prefix && '/hidden' ).
  ENDMETHOD.

  METHOD parse_createorganizationreques.
    createorganizationrequest-name = mo_json->value_string( iv_prefix && '/name' ).
    createorganizationrequest-description = mo_json->value_string( iv_prefix && '/description' ).
  ENDMETHOD.

  METHOD parse_updateorganizationdetail.
    updateorganizationdetailsreque-name = mo_json->value_string( iv_prefix && '/name' ).
    updateorganizationdetailsreque-description = mo_json->value_string( iv_prefix && '/description' ).
  ENDMETHOD.

  METHOD parse_authorizelong_termtokenr.
    authorizelong_termtokenrequest-scope = mo_json->value_string( iv_prefix && '/scope' ).
    authorizelong_termtokenrequest-organization_id = mo_json->value_string( iv_prefix && '/organization_id' ).
  ENDMETHOD.

  METHOD parse_authenticationrequest.
    authenticationrequest-email = mo_json->value_string( iv_prefix && '/email' ).
    authenticationrequest-password = mo_json->value_string( iv_prefix && '/password' ).
  ENDMETHOD.

  METHOD parse_createuserrequest.
    createuserrequest-email = mo_json->value_string( iv_prefix && '/email' ).
    createuserrequest-first_name = mo_json->value_string( iv_prefix && '/first_name' ).
    createuserrequest-last_name = mo_json->value_string( iv_prefix && '/last_name' ).
  ENDMETHOD.

  METHOD parse_updateuserrequest.
    updateuserrequest-email = mo_json->value_string( iv_prefix && '/email' ).
    updateuserrequest-first_name = mo_json->value_string( iv_prefix && '/first_name' ).
    updateuserrequest-last_name = mo_json->value_string( iv_prefix && '/last_name' ).
    updateuserrequest-password = mo_json->value_string( iv_prefix && '/password' ).
  ENDMETHOD.

  METHOD zif_Ident~createapplication.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/applications'.
    mi_client->request->set_method( 'POST' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'name' value = name ).
* todo, set body, #/components/schemas/CreateapplicationRequest
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~listapplications.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/applications'.
    mi_client->request->set_method( 'GET' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~associateusertoapplication.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/applications/{application_id}/users'.
    lv_temp = application_id.
    lv_temp = cl_http_utility=>escape_url( condense( lv_temp ) ).
    REPLACE ALL OCCURRENCES OF '{application_id}' IN lv_uri WITH lv_temp.
    mi_client->request->set_method( 'POST' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
* todo, set body, #/components/schemas/AssociateusertoapplicationRequest
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~listapplicationusers.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/applications/{application_id}/users'.
    lv_temp = application_id.
    lv_temp = cl_http_utility=>escape_url( condense( lv_temp ) ).
    REPLACE ALL OCCURRENCES OF '{application_id}' IN lv_uri WITH lv_temp.
    mi_client->request->set_method( 'GET' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'content-type' value = content_type ).
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~getapplicationdetails.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/applications/{application_id}'.
    lv_temp = application_id.
    lv_temp = cl_http_utility=>escape_url( condense( lv_temp ) ).
    REPLACE ALL OCCURRENCES OF '{application_id}' IN lv_uri WITH lv_temp.
    mi_client->request->set_method( 'GET' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'content-type' value = content_type ).
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~updateapplication.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/applications/{application_id}'.
    lv_temp = application_id.
    lv_temp = cl_http_utility=>escape_url( condense( lv_temp ) ).
    REPLACE ALL OCCURRENCES OF '{application_id}' IN lv_uri WITH lv_temp.
    mi_client->request->set_method( 'PUT' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'name' value = name ).
* todo, set body, #/components/schemas/UpdateapplicationRequest
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~deleteapplication.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/applications/{application_id}'.
    lv_temp = application_id.
    lv_temp = cl_http_utility=>escape_url( condense( lv_temp ) ).
    REPLACE ALL OCCURRENCES OF '{application_id}' IN lv_uri WITH lv_temp.
    mi_client->request->set_method( 'DELETE' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'content-type' value = content_type ).
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~listorganizations.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/organizations'.
    mi_client->request->set_method( 'GET' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'content-type' value = content_type ).
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~createorganization.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/organizations'.
    mi_client->request->set_method( 'POST' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'name' value = name ).
* todo, set body, #/components/schemas/CreateorganizationRequest
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~getorganizationdetails.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/organizations/{organization_id}'.
    lv_temp = organization_id.
    lv_temp = cl_http_utility=>escape_url( condense( lv_temp ) ).
    REPLACE ALL OCCURRENCES OF '{organization_id}' IN lv_uri WITH lv_temp.
    mi_client->request->set_method( 'GET' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'content-type' value = content_type ).
    mi_client->request->set_header_field( name = 'name' value = name ).
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~updateorganizationdetails.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/organizations/{organization_id}'.
    lv_temp = organization_id.
    lv_temp = cl_http_utility=>escape_url( condense( lv_temp ) ).
    REPLACE ALL OCCURRENCES OF '{organization_id}' IN lv_uri WITH lv_temp.
    mi_client->request->set_method( 'PUT' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'name' value = name ).
* todo, set body, #/components/schemas/UpdateorganizationdetailsRequest
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~listtokens.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/tokens'.
    mi_client->request->set_method( 'GET' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'content-type' value = content_type ).
    mi_client->request->set_header_field( name = 'name' value = name ).
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~authorizelong_termtoken.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/tokens'.
    mi_client->request->set_method( 'POST' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
* todo, set body, #/components/schemas/Authorizelong-termtokenRequest
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~updateuser.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/tokens'.
    mi_client->request->set_method( 'PUT' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'name' value = name ).
* todo, set body, #/components/schemas/UpdateuserRequest
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~revoketoken.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/tokens/f2202ba1-e2af-4505-9b1a-53e1ce8de904'.
    mi_client->request->set_method( 'DELETE' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'content-type' value = content_type ).
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~authentication.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/authenticate'.
    mi_client->request->set_method( 'POST' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
* todo, set body, #/components/schemas/AuthenticationRequest
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~listuserscopy.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/users'.
    mi_client->request->set_method( 'GET' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'content-type' value = content_type ).
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~createuser.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/users'.
    mi_client->request->set_method( 'POST' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
* todo, set body, #/components/schemas/CreateuserRequest
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~getuserdetail.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/users/{user_id}'.
    lv_temp = user_id.
    lv_temp = cl_http_utility=>escape_url( condense( lv_temp ) ).
    REPLACE ALL OCCURRENCES OF '{user_id}' IN lv_uri WITH lv_temp.
    mi_client->request->set_method( 'GET' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'content-type' value = content_type ).
    mi_client->request->set_header_field( name = 'name' value = name ).
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

  METHOD zif_Ident~deleteuser.
    DATA lv_code TYPE i.
    DATA lv_temp TYPE string.
    DATA lv_uri TYPE string VALUE '/api/v1/tokens/{user_id}'.
    lv_temp = user_id.
    lv_temp = cl_http_utility=>escape_url( condense( lv_temp ) ).
    REPLACE ALL OCCURRENCES OF '{user_id}' IN lv_uri WITH lv_temp.
    mi_client->request->set_method( 'DELETE' ).
    mi_client->request->set_header_field( name = '~request_uri' value = lv_uri ).
    mi_client->request->set_header_field( name = 'content-type' value = content_type ).
    lv_code = send_receive( ).
    WRITE / lv_code.
    CASE lv_code.
      WHEN 200.
    ENDCASE.
  ENDMETHOD.

ENDCLASS.
